rootProject.name = "evola"

include(
    ":core:domain-kernel",
    ":core:application-kernel",
    ":contexts:learner-identity:domain",
    ":contexts:learner-identity:application",
    ":contexts:learner-identity:infrastructure",
    ":contexts:vocabulary:domain",
    ":contexts:vocabulary:application",
    ":contexts:vocabulary:infrastructure",
    ":contexts:exercise-generation:application",
    ":contexts:exercise-generation:infrastructure",
    ":contexts:tutoring:domain",
    ":contexts:tutoring:application",
    ":contexts:tutoring:infrastructure",
    ":contexts:learning-resources:domain",
    ":contexts:learning-resources:application",
    ":contexts:learning-resources:infrastructure",
    ":integrations:ai-gateway",
    ":integrations:persistence-shared",
    ":presentation:telegram-bot",
    ":presentation:mini-app-api",
    ":composition-root",
)
