INSERT INTO vocabulary_items (german_word, english_translation, cefr_level, part_of_speech) VALUES
('das Haus', 'house', 'A2.2', 'noun'),
('die Wohnung', 'apartment', 'A2.2', 'noun'),
('der Termin', 'appointment', 'A2.2', 'noun'),
('die Erfahrung', 'experience', 'B1', 'noun'),
('die Erlaubnis', 'permission', 'B1', 'noun'),
('der Umzug', 'move (relocation)', 'B1', 'noun'),
('die Bewerbung', 'job application', 'B1', 'noun'),
('der Vertrag', 'contract', 'B1', 'noun'),
('die Versicherung', 'insurance', 'B1', 'noun'),
('das Gehalt', 'salary', 'B1', 'noun'),
('die Rechnung', 'invoice/bill', 'A2.2', 'noun'),
('der Nachbar', 'neighbor', 'A2.2', 'noun'),
('die Gesundheit', 'health', 'A2.2', 'noun'),
('die Verabredung', 'date/meetup', 'B1', 'noun'),
('das Ziel', 'goal', 'B1', 'noun'),
('die Entscheidung', 'decision', 'B1', 'noun'),
('die Meinung', 'opinion', 'A2.2', 'noun'),
('der Vorschlag', 'suggestion', 'B1', 'noun'),
('die Verantwortung', 'responsibility', 'B1', 'noun'),
('der Fortschritt', 'progress', 'B1', 'noun'),
('die Ausbildung', 'vocational training', 'B1', 'noun'),
('die Bewerbungsunterlagen', 'application documents', 'B1', 'noun'),
('der Umweltschutz', 'environmental protection', 'B1', 'noun'),
('die Miete', 'rent', 'A2.2', 'noun'),
('der Vermieter', 'landlord', 'A2.2', 'noun'),
('die Kündigung', 'termination/notice', 'B1', 'noun'),
('das Vorstellungsgespräch', 'job interview', 'B1', 'noun'),
('die Kollegin', 'female colleague', 'A2.2', 'noun'),
('der Kollege', 'male colleague', 'A2.2', 'noun'),
('die Besprechung', 'meeting', 'B1', 'noun'),
('der Unterschied', 'difference', 'B1', 'noun'),
('die Gelegenheit', 'opportunity', 'B1', 'noun'),
('die Beschwerde', 'complaint', 'B1', 'noun'),
('das Anliegen', 'concern/request', 'B1', 'noun'),
('die Rücksicht', 'consideration', 'B1', 'noun'),
('erreichen', 'to reach/achieve', 'B1', 'verb'),
('sich bewerben', 'to apply (for a job)', 'B1', 'verb'),
('vermeiden', 'to avoid', 'B1', 'verb'),
('sich entscheiden', 'to decide', 'B1', 'verb'),
('empfehlen', 'to recommend', 'B1', 'verb'),
('sich beschweren', 'to complain', 'B1', 'verb'),
('vereinbaren', 'to arrange/agree on', 'B1', 'verb'),
('sich vorstellen', 'to introduce oneself / imagine', 'A2.2', 'verb'),
('umziehen', 'to move (residence)', 'A2.2', 'verb'),
('teilnehmen', 'to participate', 'B1', 'verb'),
('sich kümmern um', 'to take care of', 'B1', 'verb'),
('verbessern', 'to improve', 'B1', 'verb'),
('sich gewöhnen an', 'to get used to', 'B1', 'verb'),
('verpassen', 'to miss (an opportunity)', 'B1', 'verb'),
('sich informieren', 'to gather information', 'B1', 'verb'),
('anmelden', 'to register', 'A2.2', 'verb'),
('abmelden', 'to deregister', 'A2.2', 'verb'),
('reservieren', 'to reserve', 'A2.2', 'verb'),
('bezahlen', 'to pay', 'A2.2', 'verb'),
('reparieren', 'to repair', 'A2.2', 'verb'),
('sich beeilen', 'to hurry', 'A2.2', 'verb'),
('erledigen', 'to take care of/finish', 'B1', 'verb'),
('funktionieren', 'to function/work', 'A2.2', 'verb'),
('sich verabschieden', 'to say goodbye', 'A2.2', 'verb'),
('überweisen', 'to transfer (money)', 'B1', 'verb'),
('zunehmen', 'to increase / gain weight', 'B1', 'verb'),
('abnehmen', 'to decrease / lose weight', 'B1', 'verb'),
('dringend', 'urgent', 'B1', 'adjective'),
('zuverlässig', 'reliable', 'B1', 'adjective'),
('praktisch', 'practical', 'A2.2', 'adjective'),
('freundlich', 'friendly', 'A2.2', 'adjective'),
('bequem', 'comfortable', 'A2.2', 'adjective'),
('unabhängig', 'independent', 'B1', 'adjective'),
('erfahren', 'experienced', 'B1', 'adjective'),
('gespannt', 'curious/excited', 'B1', 'adjective'),
('erschöpft', 'exhausted', 'B1', 'adjective'),
('erfolgreich', 'successful', 'B1', 'adjective'),
('gleichzeitig', 'simultaneous', 'B1', 'adjective'),
('ausreichend', 'sufficient', 'B1', 'adjective'),
('freiwillig', 'voluntary', 'B1', 'adjective'),
('flexibel', 'flexible', 'B1', 'adjective'),
('regelmäßig', 'regular', 'A2.2', 'adjective')
ON CONFLICT (german_word) DO NOTHING;
